name: Destroy terraform resources on the given folder

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory with resources to be destroyed'
        required: true
        default: '0003-terraform-gha'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy-dev:
    name: 'terraform destroy dev'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend=true -backend-config="config/dev/backend.hcl"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="config/dev/terraform.tfvars"

  destroy-prod:
    name: 'terraform destroy prod'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend=true -backend-config="config/prod/backend.hcl"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="config/prod/terraform.tfvars"
